//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public long BLOG_ID { get; set; }
        public string BLOG_TITLE { get; set; }
        public string BLOG_CONTENT { get; set; }
        public string BLOG_CONTENT_OVERVIEW { get; set; }
        public string BLOG_URL { get; set; }
        public string BLOG_ORIGINAL_URL { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.Guid> ADDED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
    }
}
