//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIDS_CORNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIDS_CORNER()
        {
            this.KIDS_CORNER_IMAGES = new HashSet<KIDS_CORNER_IMAGES>();
        }
    
        public long ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.Guid> ADDED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KIDS_CORNER_IMAGES> KIDS_CORNER_IMAGES { get; set; }
    }
}
