//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SJEntities : DbContext
    {
        public SJEntities()
            : base("name=SJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOG> BLOGS { get; set; }
        public virtual DbSet<KIDS_CORNER> KIDS_CORNER { get; set; }
        public virtual DbSet<KIDS_CORNER_IMAGES> KIDS_CORNER_IMAGES { get; set; }
        public virtual DbSet<TRIP_IMAGES> TRIP_IMAGES { get; set; }
        public virtual DbSet<TRIP> TRIPS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
