//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP_IMAGES
    {
        public long IMAGE_ID { get; set; }
        public Nullable<long> TRIP_ID { get; set; }
        public string IMAGE_TITLE { get; set; }
        public string IMAGE_FILE { get; set; }
        public string IMAGE_DESC { get; set; }
        public string IMAGE_URL { get; set; }
        public Nullable<bool> IS_COVER { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.Guid> ADDED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
    
        public virtual TRIP TRIP { get; set; }
    }
}
