//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRIP()
        {
            this.TRIP_IMAGES = new HashSet<TRIP_IMAGES>();
        }
    
        public long TRIP_ID { get; set; }
        public string TRIP_TITLE { get; set; }
        public string TRIP_DESCRIPTION { get; set; }
        public string TRIP_URL { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.Guid> ADDED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public Nullable<System.Guid> UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRIP_IMAGES> TRIP_IMAGES { get; set; }
    }
}
