//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaiSmi.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public System.Guid USER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SALUTATION { get; set; }
        public byte[] PASSWORD { get; set; }
        public string DESCRIPTION { get; set; }
        public string URL { get; set; }
        public string PROFILE_PIC { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    }
}
